"""AdapterScaffolder — generate an AgentAdapter stub from an AgentManifest.

Pure string generation; no file I/O, no Azure calls.  The caller (harness CLI)
is responsible for writing the returned string to disk.
"""

from __future__ import annotations

import json

from hlsharness.manifest import AgentManifest, ManifestTool


def _to_class_name(agent: str) -> str:
    """Convert an agent slug to a CamelCase class name.

    Examples
    --------
    >>> _to_class_name("prior-auth-v1")
    'PriorAuthV1Adapter'
    >>> _to_class_name("scheduling-v1")
    'SchedulingV1Adapter'
    """
    return "".join(part.capitalize() for part in agent.split("-")) + "Adapter"


def _tool_definition_source(tool: ManifestTool, indent: int = 4) -> str:
    """Render a single ToolDefinition constructor call as source text."""
    pad = " " * indent
    params_json = json.dumps(tool.parameters, indent=indent + 4)
    # Indent continuation lines to align with the opening brace
    params_indented = params_json.replace("\n", f"\n{pad}        ")
    return (
        f"{pad}ToolDefinition(\n"
        f"{pad}    name={tool.name!r},\n"
        f"{pad}    description={tool.description!r},\n"
        f"{pad}    parameters={params_indented},\n"
        f"{pad})"
    )


class AdapterScaffolder:
    """Generates an ``AgentAdapter`` stub from an ``AgentManifest``.

    Usage
    -----
    ::

        scaffolder = AdapterScaffolder()
        source = scaffolder.scaffold(manifest)
        Path("hlsharness/adapters/my_agent.py").write_text(source)
    """

    def scaffold(self, manifest: AgentManifest) -> str:
        """Return Python source for an adapter stub populated from *manifest*.

        The generated stub contains a complete Azure OpenAI tool-calling loop.
        Two ``# TODO`` markers require developer attention before the adapter
        will run:

        1. The deployment env var name (search for ``AZURE_OPENAI_DEPLOYMENT_YOUR_AGENT``).
        2. The system prompt string (search for ``TODO: Replace``).

        Parameters
        ----------
        manifest:
            Validated AgentManifest to scaffold from.

        Returns
        -------
        str
            Valid Python source code. Passes ``compile()`` without error.
            The caller should write this string to
            ``hlsharness/adapters/{agent}.py``.
        """
        class_name = _to_class_name(manifest.agent)
        tools_block = self._render_tools(manifest)
        system_prompt_hint = manifest.system_prompt_hint or (
            f"You are a helpful {manifest.description.lower()}."
        )
        env_var_name = (
            "AZURE_OPENAI_DEPLOYMENT_" + manifest.agent.upper().replace("-", "_")
        )

        run_body = self._render_run_body(class_name, env_var_name)

        return (
            f'"""{class_name} — auto-generated stub.\n\n'
            f"Two TODOs remain before this adapter will run:\n"
            f"  1. Replace AZURE_OPENAI_DEPLOYMENT_YOUR_AGENT with your deployment env var name.\n"
            f"  2. Replace the system prompt string with your agent's actual system prompt.\n\n"
            f"Generated by ``hls-eval onboard``. See ARCHITECT_GUIDE.md for full details.\n"
            f'"""\n\n'
            f"from __future__ import annotations\n\n"
            f"import json\n"
            f"import os\n\n"
            f"from hlsharness.adapter import AgentAdapter, AgentResponse, ToolDefinition\n"
            f"from hlsharness.simulator import ToolSimulator\n\n"
            f"{tools_block}\n\n"
            f"class {class_name}(AgentAdapter):\n\n"
            f"    def __init__(self, max_turns: int = 10) -> None:\n"
            f"        self._max_turns = max_turns\n"
            f"        self._client = None  # lazy — avoids Azure credential lookup on import\n\n"
            f"    @property\n"
            f"    def name(self) -> str:\n"
            f"        return {manifest.agent!r}\n\n"
            f"    @property\n"
            f"    def system_prompt(self) -> str:\n"
            f"        # TODO: Replace with your agent's actual system prompt\n"
            f"        return {system_prompt_hint!r}\n\n"
            f"    @property\n"
            f"    def tools(self) -> list[ToolDefinition]:\n"
            f"        return _TOOLS\n\n"
            f"{run_body}\n"
            f"    # ── internal ──────────────────────────────────────────────────────────\n\n"
            f"    def _get_client(self) -> object:  # pragma: no cover\n"
            f"        if self._client is None:\n"
            f"            from azure.identity import DefaultAzureCredential, get_bearer_token_provider\n"
            f"            from openai import AzureOpenAI\n\n"
            f"            credential = DefaultAzureCredential()\n"
            f"            token_provider = get_bearer_token_provider(\n"
            f"                credential, 'https://cognitiveservices.azure.com/.default'\n"
            f"            )\n"
            f"            self._client = AzureOpenAI(\n"
            f"                azure_endpoint=os.environ.get('AZURE_OPENAI_ENDPOINT', ''),\n"
            f"                azure_ad_token_provider=token_provider,\n"
            f"                api_version='2025-01-01-preview',\n"
            f"            )\n"
            f"        return self._client\n"
        )

    @staticmethod
    def _render_run_body(class_name: str, env_var_name: str) -> str:
        return (
            f"    def run(\n"
            f"        self,\n"
            f"        messages: list[dict[str, object]],\n"
            f"        tool_simulator: ToolSimulator,\n"
            f"    ) -> AgentResponse:  # pragma: no cover\n"
            f"        client = self._get_client()\n"
            f"        # TODO: Replace AZURE_OPENAI_DEPLOYMENT_YOUR_AGENT with your deployment env var name\n"
            f"        deployment = os.environ.get({env_var_name!r}, 'gpt-5.4-nano')\n\n"
            f"        openai_tools = [\n"
            f"            {{'type': 'function', 'function': {{\n"
            f"                'name': t.name,\n"
            f"                'description': t.description,\n"
            f"                'parameters': t.parameters,\n"
            f"            }}}}\n"
            f"            for t in self.tools\n"
            f"        ]\n\n"
            f"        conversation: list[dict[str, object]] = [\n"
            f"            {{'role': 'system', 'content': self.system_prompt}},\n"
            f"            *messages,\n"
            f"        ]\n"
            f"        prompt_tokens = completion_tokens = 0\n\n"
            f"        for _ in range(self._max_turns):\n"
            f"            response = client.chat.completions.create(  # type: ignore[union-attr]\n"
            f"                model=deployment,\n"
            f"                messages=conversation,  # type: ignore[arg-type]\n"
            f"                tools=openai_tools,  # type: ignore[arg-type]\n"
            f"                tool_choice='auto',\n"
            f"            )\n"
            f"            if response.usage:\n"
            f"                prompt_tokens += response.usage.prompt_tokens\n"
            f"                completion_tokens += response.usage.completion_tokens\n\n"
            f"            message = response.choices[0].message\n\n"
            f"            if not message.tool_calls:\n"
            f"                return AgentResponse(\n"
            f"                    content=message.content or '',\n"
            f"                    trajectory=tool_simulator.trajectory,\n"
            f"                    prompt_tokens=prompt_tokens,\n"
            f"                    completion_tokens=completion_tokens,\n"
            f"                )\n\n"
            f"            conversation.append(message.model_dump(exclude_unset=True))\n\n"
            f"            for tc in message.tool_calls:\n"
            f"                arguments = json.loads(tc.function.arguments)\n"
            f"                result = tool_simulator.call(tc.function.name, arguments)\n"
            f"                conversation.append({{\n"
            f"                    'role': 'tool',\n"
            f"                    'tool_call_id': tc.id,\n"
            f"                    'content': json.dumps(result),\n"
            f"                }})\n\n"
            f"            tool_simulator.advance_turn()\n\n"
            f"        raise RuntimeError(\n"
            f"            f'{{{class_name!r}}}.run() exceeded max_turns={{self._max_turns}} '\n"
            f"            'without producing a final response.'\n"
            f"        )\n\n"
        )

    # ── internal ──────────────────────────────────────────────────────────────

    @staticmethod
    def _render_tools(manifest: AgentManifest) -> str:
        if not manifest.tools:
            return "_TOOLS: list[ToolDefinition] = []"
        tool_lines = ",\n".join(_tool_definition_source(t) for t in manifest.tools)
        return f"_TOOLS = [\n{tool_lines},\n]"

