"""AdapterScaffolder — generate an AgentAdapter stub from an AgentManifest.

Pure string generation; no file I/O, no Azure calls.  The caller (harness CLI)
is responsible for writing the returned string to disk.
"""

from __future__ import annotations

import json

from hlsharness.manifest import AgentManifest, ManifestTool


def _to_class_name(agent: str) -> str:
    """Convert an agent slug to a CamelCase class name.

    Examples
    --------
    >>> _to_class_name("prior-auth-v1")
    'PriorAuthV1Adapter'
    >>> _to_class_name("scheduling-v1")
    'SchedulingV1Adapter'
    """
    return "".join(part.capitalize() for part in agent.split("-")) + "Adapter"


def _tool_definition_source(tool: ManifestTool, indent: int = 4) -> str:
    """Render a single ToolDefinition constructor call as source text."""
    pad = " " * indent
    params_json = json.dumps(tool.parameters, indent=indent + 4)
    # Indent continuation lines to align with the opening brace
    params_indented = params_json.replace("\n", f"\n{pad}        ")
    return (
        f"{pad}ToolDefinition(\n"
        f"{pad}    name={tool.name!r},\n"
        f"{pad}    description={tool.description!r},\n"
        f"{pad}    parameters={params_indented},\n"
        f"{pad})"
    )


class AdapterScaffolder:
    """Generates an ``AgentAdapter`` stub from an ``AgentManifest``.

    Usage
    -----
    ::

        scaffolder = AdapterScaffolder()
        source = scaffolder.scaffold(manifest)
        Path("hlsharness/adapters/my_agent.py").write_text(source)
    """

    def scaffold(self, manifest: AgentManifest) -> str:
        """Return Python source for an adapter stub populated from *manifest*.

        Parameters
        ----------
        manifest:
            Validated AgentManifest to scaffold from.

        Returns
        -------
        str
            Valid Python source code. Passes ``ast.parse()`` without error.
            The caller should write this string to
            ``hlsharness/adapters/{agent}.py``.
        """
        class_name = _to_class_name(manifest.agent)
        tools_block = self._render_tools(manifest)
        system_prompt = manifest.system_prompt_hint or (
            f"You are a helpful {manifest.description.lower()}."
        )

        return (
            f'"""{class_name} — auto-generated stub. Implement run() to activate.\n\n'
            f"Generated by ``hls-eval onboard``. See ARCHITECT_GUIDE.md for a walkthrough.\n"
            f'"""\n\n'
            f"from __future__ import annotations\n\n"
            f"from hlsharness.adapter import AgentAdapter, AgentResponse, ToolDefinition\n"
            f"from hlsharness.simulator import ToolSimulator\n\n"
            f"{tools_block}\n\n"
            f"class {class_name}(AgentAdapter):\n\n"
            f"    @property\n"
            f"    def name(self) -> str:\n"
            f"        return {manifest.agent!r}\n\n"
            f"    @property\n"
            f"    def system_prompt(self) -> str:\n"
            f"        return {system_prompt!r}\n\n"
            f"    @property\n"
            f"    def tools(self) -> list[ToolDefinition]:\n"
            f"        return _TOOLS\n\n"
            f"    def run(\n"
            f"        self,\n"
            f"        messages: list[dict[str, object]],\n"
            f"        tool_simulator: ToolSimulator,\n"
            f"    ) -> AgentResponse:\n"
            f"        raise NotImplementedError(\n"
            f"            {class_name!r} + '.run() is not yet implemented — '\n"
            f"            'see ARCHITECT_GUIDE.md for a complete walkthrough.'\n"
            f"        )\n"
        )

    # ── internal ──────────────────────────────────────────────────────────────

    @staticmethod
    def _render_tools(manifest: AgentManifest) -> str:
        if not manifest.tools:
            return "_TOOLS: list[ToolDefinition] = []"
        tool_lines = ",\n".join(_tool_definition_source(t) for t in manifest.tools)
        return f"_TOOLS = [\n{tool_lines},\n]"
